// see https://helmetjs.github.io/docs/feature-policy/
const featurePolicy = {
  features: {
    accelerometer: ["'none'"],
    ambientLightSensor: ["'none'"],
    autoplay: ["'none'"],
    camera: ["'none'"],
    documentDomain: ["'none'"],
    documentWrite: ["'none'"],
    encryptedMedia: ["'none'"],
    fontDisplayLateSwap: ["'none'"],
    fullscreen: ["'none'"],
    geolocation: ["'none'"],
    gyroscope: ["'none'"],
    layoutAnimations: ["'none'"],
    legacyImageFormats: ["'none'"],
    loadingFrameDefaultEager: ["'none'"],
    magnetometer: ["'none'"],
    microphone: ["'none'"],
    midi: ["'none'"],
    oversizedImages: ["'none'"],
    payment: ["'none'"],
    pictureInPicture: ["'none'"],
    serial: ["'none'"],
    speaker: ["'none'"],
    syncScript: ["'none'"],
    syncXhr: ["'none'"],
    unoptimizedImages: ["'none'"],
    unoptimizedLosslessImages: ["'none'"],
    unoptimizedLossyImages: ["'none'"],
    unsizedMedia: ["'none'"],
    usb: ["'none'"],
    verticalScroll: ["'none'"],
    vibrate: ["'none'"],
    vr: ["'none'"],
    wakeLock: ["'none'"],
    xr: ["'none'"],
  },
}

export default featurePolicy
